name: Release bspwm

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxcb-util-dev libxcb-keysyms1-dev libxcb-icccm4-dev \
          libxcb-ewmh-dev libxcb-randr0-dev libxcb-xinerama0-dev libxcb-shape0-dev

    - name: Build
      run: make

    - name: Strip binaries
      run: strip bspwm bspc

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bspwm
          bspc
